### ISSUE TITLE
Doesn't work with non default namespace?

### ISSUE THREAD

**Issue by Anahkiasen** [NoelDeMartin/laravel-cypress#3]
I use the name of my project as namespace, but in `CypressController` you use the default [controller namespace](https://github.com/NoelDeMartin/laravel-cypress/blob/master/src/Http/Controllers/CypressController.php#L5) which crashes for me. Could it be made configurable?

**Comment by NoelDeMartin** [comment]
Thanks for opening the issue!

Actually, it doesn't even need to extend a controller class, I just did it out of habit.

Update to version v0.1.1 and it should work.

**Comment by Anahkiasen** [comment]
Nice, thanks!
