### ISSUE TITLE
Transactional tests

### ISSUE THREAD

**Issue by carlobeltrame** [NoelDeMartin/laravel-cypress#4]
Hi, thanks for this package!

In larger applications, setting up the database might take a while. At the same time, it is [a best practice](https://docs.cypress.io/guides/references/best-practices.html#Having-tests-rely-on-the-state-of-previous-tests) (not only in Cypress) to decouple tests so they can run independently. For this reason, Laravel has the [DatabaseTransactions](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Testing/DatabaseTransactions.php) and [RefreshDatabase](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Testing/RefreshDatabase.php) traits.

I'd like to use a similar automated mechanic for Cypress E2E tests. Specifically, I think we'd need two (?) additional endpoints to start and end a transaction before and after each test respectively.

Is this something that you see as useful as well? I'd be happy to create a PR for it if there is interest.

**Comment by NoelDeMartin** [comment]
Hi there, thanks for opening the issue :).

This was actually the default behaviour in the initial version, but I refactored it into a dedicated method after [this issue was raised](https://github.com/NoelDeMartin/laravel-cypress/issues/2). However, those traits cannot be used for Cypress tests, you can find the reason [documented in the Dusk documentation](https://laravel.com/docs/7.x/dusk#migrations) given that it's the same problem. In Dusk, there is a trait called `DatabaseMigrations` and that should be used instead.

In Cypress, you can do the same calling the `useDatabaseMigrations` method as you can see [in this example](https://github.com/NoelDeMartin/laravel-cypress-sandbox/blob/master/cypress/integration/auth.spec.js#L5).

**Comment by carlobeltrame** [comment]
Thanks, I actually knew about the migration approach, but that isn't what I'm looking for. As I said, in some applications, migrating and seeding the database to a useable state can take a long time. So long that it isn't desirable to run it before every test in a test suite.
I was looking for a way to use a large wrapping database transaction around each test, and was planning to set this up using a laravel-cypress endpoint that starts a transaction (i.e. makes a savepoint), and a separate endpoint that rolls back that transaction after the test has finished. This could even be nested to set up more specific test environments for nested contexts, but would only support database engines that can do savepoints (InnoDB in MySQL can, for example).

However, this approach didn't work in my experiments, because Laravel closes all transactions and savepoints after every request (I think), so after the "create transaction" call is finished, the transaction is closed right away before the test can even run.

I ended up using the package [laravel-db-snapshots](https://github.com/spatie/laravel-db-snapshots) and creating two endpoints to create and restore such snapshots. I think it would go too far to include that in laravel-cypress. So unless you think otherwise, I'm going to keep that solution in my project rather than opening a PR for it.

**Comment by NoelDeMartin** [comment]
> I ended up using the package laravel-db-snapshots and creating two endpoints to create and restore such snapshots. I think it would go too far to include that in laravel-cypress. So unless you think otherwise, I'm going to keep that solution in my project rather than opening a PR for it.

Yes that'd be outside of the scope of this package, but I'll add support for custom commands as I mentioned in [this issue](https://github.com/NoelDeMartin/cypress-laravel/issues/3). So maybe that allows you to clean up your code bit.

I haven't used the `laravel-db-snapshots` package, but I've used the sqlite driver and you can use it with a local file that you can override for each test. Not sure which approach will be faster though.
