### ISSUE TITLE
callArtisan to return console output as JSON

### ISSUE THREAD

**Issue by ianjamieson** [NoelDeMartin/laravel-cypress#9]
In my use case I am running an artisan command, and I would like to get the output of that command to use in my test.

**Comment by ianjamieson** [comment]
Ah sorry I tried to make a PR to fix this, basically I just added a return to the `callArtisan` method here:

https://github.com/NoelDeMartin/laravel-cypress/blob/5828dec27ee7bfe959c2213553fe1ee5fe209ef0/src/Http/Controllers/CypressController.php#L53-L58

Like this:

```php
return response()->json(Artisan::output());
```

**Comment by NoelDeMartin** [comment]
I haven't tried it, but it looks good to me. Do you want to open a PR? I'd probably merge it :).

**Comment by ianjamieson** [comment]
@NoelDeMartin - sure, I would have done but I don't have write permissions to create a new branch :(

**Comment by NoelDeMartin** [comment]
You don't need write permissions to do that :). Is this your first time making a contribution in github? I'm happy to help you, if you want.

Basically, you need to create your fork of this repository (click on the "fork" button at the top right of the page). Then, you'll have a repository you own with the same code as this one. Then, you can create a new branch and do whatever you like on your repository. Once you have a branch with the proposed changes, you can open a pull request from your fork to this repo. It will look like #6. You can notice that he did all the changes on his own repo at https://github.com/takdw/laravel-cypress/tree/laravel-factories

You can learn more about this in the github docs: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Feel free to ask any doubts :).
